version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/Paris"
    assignees:
      - "TheophileDiot"
    commit-message:
      prefix: "deps/gha"
    target-branch: "main"

  - package-ecosystem: "docker-compose"
    directory: "/tests"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/Paris"
    assignees:
      - "TheophileDiot"
    commit-message:
      prefix: "deps/tests"
    target-branch: "main"
